# Generated by Django 3.0.6 on 2020-06-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20200604_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_image_db',
            field=models.CharField(max_length=2048, unique=True, verbose_name='URL-адрес изображения'),
        ),
    ]
